[project]
name = "erpgenex_theme_0426"
authors = [{ name = "ErpGenEx", email = "dev@erpgenex.com"}]
description = "ERPGenEx Desk theme 0426 (enterprise desk styling; optional business_theme-inspired polish)."
requires-python = ">=3.10"
readme = "README.md"
version = "0.1.0"
dependencies = []

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.ruff]
line-length = 110
target-version = "py310"
